### ISSUE TITLE
Calling backend

### ISSUE THREAD

**Issue by ghost** [adamlofts/angular_quill#1]
I am building this into a webview to run on desktops as a quicky prototype.

Here is the webview runner in golang. This is a typical example.

https://github.com/zserge/webview/tree/master/examples/counter-go

My question relates to how to get quill dart code to call javascript code that I also inject into the page ? The webview backend has a very simple to mechanism. Hopefully you can see it in the link.

Do I need to wrap your component or can I use dependency injection to tell the component a Js call to make when a content changed event happens ? I want to call the backend on every content change as I store state there :)

Thanks in advance 
I will put this demo up on GitHub once I get it all working..

**Comment by adamlofts** [comment]
Do you have a dart angular app up and running already? If you do then you can listen to the events on the quill component and run js code using the webview apis.

If you don't have angular working then this would be the first step. You would need to call bootstrap to run dependency injection and start the app.

**Comment by ghost** [comment]
thanks adam.
If you know of an example ??

**Comment by adamlofts** [comment]
An example of an angular app in a webview? no. I'd ask the angulardart team about that directly.
